[build]
  command = "bash build.sh"
  publish = "build/site"
  secrets_scan_enabled = false
  timeout = 1800

[[redirects]]
  from = "/product-docs/6.2/*.html"
  to = "/product-docs/6.2/:splat"
  status = 301

[[redirects]]
  from = "/product-docs/6.2/*"
  to = "/product-docs/6.2/:splat"
  status = 301

[[redirects]]
  from = "/product-docs/6.3/*"
  to = "/product-docs/6.3/:splat"
  status = 301

[[redirects]]
  from = "/product-docs/*"
  to = "/product-docs/6.3/:splat"
  status = 301